name: release-otoroshi-swagger-ui-plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: setup jdk21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: coursier/cache-action@v6
      - uses: sbt/setup-sbt@v1
      - name: change version
        run: |
          echo 'ThisBuild / version := "${{ inputs.version }}"' > version.sbt
      - name: build-libs
        id: build-libs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sbt ';compile;package'
      - name: Generate SHA-256
        run: |
          shasum -a 256 ./target/scala-2.12/otoroshi-swagger-ui-plugin_2.12-${{ inputs.version }}.jar | cut -d ' ' -f 1 > ./target/scala-2.12/otoroshi-swagger-ui-plugin_2.12-${{ inputs.version }}.jar.sha256
      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          files: |
            ./target/scala-2.12/otoroshi-swagger-ui-plugin_2.12-${{ inputs.version }}.jar
            ./target/scala-2.12/otoroshi-swagger-ui-plugin_2.12-${{ inputs.version }}.jar.sha256
